### ISSUE TITLE
Intermediate test error?

### ISSUE THREAD

**Issue by brianignacio5** [moritzschaefer/the-search-engine#40]
Hey Moritz:

Can you check this error in test:

FAIL: reads a json file and counts the words occurences
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/bignacio/Escritorio/the-search-engine/test/test_intermediate.py", line 34, in test_generate_intermediate
    eq_(target_file.read(), output_file.read())
AssertionError: 'uuid,type,title,isbn,content\n598859a0-eaa7-466a-8919-e6260c89edef,0,1,0,3\n31a8e3b4-8c67-4fb7-b11a-1df1105617a2,0,1,0,1\n' != 'uuid,type,title,isbn,content\n598859a0-eaa7-466a-8919-e6260c89edef,0,1,0,3\n31a8e3b4-8c67-4fb7-b11a-1df1105617a2,0,1,0,1\n598859a0-eaa7-466a-8919-e6260c89edef,0,1,0,3\n31a8e3b4-8c67-4fb7-b11a-1df1105617a2,0,1,0,1\n598859a0-eaa7-466a-8919-e6260c89edef,0,1,0,3\n31a8e3b4-8c67-4fb7-b11a-1df1105617a2,0,1,0,1\n598859a0-eaa7-466a-8919-e6260c89edef,0,1,0,3\n31a8e3b4-8c67-4fb7-b11a-1df1105617a2,0,1,0,1\n598859a0-eaa7-466a-8919-e6260c89edef,0,1,0,3\n31a8e3b4-8c67-4fb7-b11a-1df1105617a2,0,1,0,1\n598859a0-eaa7-466a-8919-e6260c89edef,0,1,0,3\n31a8e3b4-8c67-4fb7-b11a-1df1105617a2,0,1,0,1\n598859a0-eaa7-466a-8919-e6260c89edef,0,1,0,3\n31a8e3b4-8c67-4fb7-b11a-1df1105617a2,0,1,0,1\n'

Maybe i need some file or something different in my libraries?

**Comment by moritzschaefer** [comment]
for some strange reason it doesn't delete the file... 
do the following:
in config.py 
in line 7 add this:
import ipbd; ipdb.set_trace()
then run nosetests.
it will open a shell (if you don't have ipdb, install it with pip).
execute:
p sys.argv[0]

print the outcome here.

**Comment by moritzschaefer** [comment]
I think it should be "contains" instead of "endswith" (check the code).

**Comment by brianignacio5** [comment]
I will check this now. Will edit this response in a while.

**Comment by brianignacio5** [comment]
bignacio@bignacio-Lenovo-IdeaPad-Y400:~/Escritorio/the-search-engine$ nosetests3 test/test_intermediate.py
E
======================================================================
ERROR: Failure: TypeError (bad argument type for built-in operation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/bignacio/Escritorio/the-search-engine/test/test_intermediate.py", line 6, in <module>
    from tsg.intermediate.base import process_document
  File "/home/bignacio/Escritorio/the-search-engine/tsg/__init__.py", line 1, in <module>
    from tsg.search import search
  File "/home/bignacio/Escritorio/the-search-engine/tsg/search.py", line 1, in <module>
    from tsg.parser import parse_text
  File "/home/bignacio/Escritorio/the-search-engine/tsg/parser/__init__.py", line 1, in <module>
    from tsg.parser.base import parse_document, parse_text
  File "/home/bignacio/Escritorio/the-search-engine/tsg/parser/base.py", line 8, in <module>
    from tsg.config import PARSED_DIR
  File "/home/bignacio/Escritorio/the-search-engine/tsg/config.py", line 10, in <module>
    if TESTING:
  File "/home/bignacio/Escritorio/the-search-engine/tsg/config.py", line 10, in <module>
    if TESTING:
  File "/usr/lib/python3.4/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.4/bdb.py", line 66, in dispatch_line
    self.user_line(frame)
  File "/usr/lib/python3.4/pdb.py", line 259, in user_line
    self.interaction(frame, None)
  File "/usr/lib/python3/dist-packages/IPython/core/debugger.py", line 268, in interaction
    OldPdb.interaction(self, frame, traceback)
  File "/usr/lib/python3.4/pdb.py", line 346, in interaction
    self._cmdloop()
  File "/usr/lib/python3.4/pdb.py", line 319, in _cmdloop
    self.cmdloop()
  File "/usr/lib/python3.4/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
TypeError: bad argument type for built-in operation

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
